// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALQuFJk2rlqinn2J21uTDPloZ-BWm5aEk',
    appId: '1:1063266749253:web:1bd323d37333946c7b8c2c',
    messagingSenderId: '1063266749253',
    projectId: 'svastha-f2785',
    authDomain: 'svastha-f2785.firebaseapp.com',
    databaseURL: 'https://svastha-f2785-default-rtdb.firebaseio.com',
    storageBucket: 'svastha-f2785.firebasestorage.app',
    measurementId: 'G-EFY8G8T3KX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTmVODJ-ZJ26Fmq6PbEB0UWnt_uVmG_QY',
    appId: '1:1063266749253:android:2fe7e8aa2c0640677b8c2c',
    messagingSenderId: '1063266749253',
    projectId: 'svastha-f2785',
    databaseURL: 'https://svastha-f2785-default-rtdb.firebaseio.com',
    storageBucket: 'svastha-f2785.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH7PtClz681WO-xxDq4YsZJrg0WBjNggk',
    appId: '1:1063266749253:ios:a5bcb94aca8a93b07b8c2c',
    messagingSenderId: '1063266749253',
    projectId: 'svastha-f2785',
    databaseURL: 'https://svastha-f2785-default-rtdb.firebaseio.com',
    storageBucket: 'svastha-f2785.firebasestorage.app',
    iosBundleId: 'com.example.farmerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH7PtClz681WO-xxDq4YsZJrg0WBjNggk',
    appId: '1:1063266749253:ios:a5bcb94aca8a93b07b8c2c',
    messagingSenderId: '1063266749253',
    projectId: 'svastha-f2785',
    databaseURL: 'https://svastha-f2785-default-rtdb.firebaseio.com',
    storageBucket: 'svastha-f2785.firebasestorage.app',
    iosBundleId: 'com.example.farmerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALQuFJk2rlqinn2J21uTDPloZ-BWm5aEk',
    appId: '1:1063266749253:web:b60b1c2819f945ec7b8c2c',
    messagingSenderId: '1063266749253',
    projectId: 'svastha-f2785',
    authDomain: 'svastha-f2785.firebaseapp.com',
    databaseURL: 'https://svastha-f2785-default-rtdb.firebaseio.com',
    storageBucket: 'svastha-f2785.firebasestorage.app',
    measurementId: 'G-E5X2490YJM',
  );
}
